######### Making map of RRC Sites #####
install.packages("lubridate")
install.packages("measurements")
install.packages("sf")
install.packages("rnaturalearth")
install.packages("rnaturalearthhires")
install.packages("pacman")
install.packages("tidyverse")
library(pacman)
library(tidyverse)
library(lubridate)
library(measurements)
library(sf)
library(rnaturalearth)
library(rnaturalearthhires)
setwd("~/Documents/GitHub/RRCOrbicella/OfavKoko/RRC_LATLONG")

ofavSamples = read.csv("updatedRRC_LatLong.csv", header = TRUE) %>% select(sample = Sample, !sampleID)
ofavSamples$Resistance = factor(ofavSamples$Resistance, levels = levels(ofavSamples$Resistance)[c(3,2,1)])
ofavSamples$Site = factor(ofavSamples$Site, levels = levels(ofavSamples$Site)[c(5, 4, 1, 3, 2)])

ofavPops = ofavSamples %>% group_by(Site) %>% summarize(latDD = mean(latDD), longDD = mean(lonDD), n = n()) %>% droplevels()
## `summarise()` ungrouping output (override with `.groups` argument)
ofavSampleSites = ofavSamples %>% group_by(Site, Resistance) %>% summarize(latDD = min(latDD), longDD = min(lonDD))
## `summarise()` regrouping output by 'region', 'site' (override with `.groups` argument)

states = st_as_sf(ne_states(country = c("United States of America")))
countries = st_as_sf(ne_countries(country = c("Cuba", "The Bahamas")))
florida = read_sf("flCountiesLo.shp") %>% st_transform(crs = 4326)
frt = read_sf("flReefs.shp") %>% st_transform(crs = 4326)

